### ISSUE TITLE
Break down your sass files

### ISSUE THREAD

**Issue by gepetobio** [brandonpowell/ireconcile-theme#2]
Try to avoid having really long scss files by breaking them down in components/modules. For example, you can create a `_header.scss` file and just add the css related to the header of your website. The same for footer, sidebar etc. You can even create specific files for typography, colors, variables etc. Then you include them all like this in the main scss file:

```
@import "vendor/print";
@import "vendor/normalize"; 
@import "toolbox/fonts";
@import "toolbox/colors";
@import "toolbox/variables";
@import "toolbox/toolbox";
@import "toolbox/z-index";

@import "global/typography";
@import "global/global";
@import "global/header";
@import "global/footer";
```

Remember to name these other scss files with a `_` in the beginning so they don't generate new css files.

**Comment by brandonpowell** [comment]
Done
